config/routes.rb
Wishlist::Application.routes.draw do
  namespace :admin do
    resources :wishes do
     post 'sort', :on => :collection
     post 'toggle_public', :on => :member
    end
  end

  resources :wishes, :only => [:index, :show] do
    post 'prepare_claim', :on => :member
    get 'claim', :on => :member

    match 'owner_protection', :on => :collection, :action => :owner_protection
    match 'visitor', :on => :collection, :action => :visitor
    match 'owner', :on => :collection, :action => :owner
    match 'howto', :on => :collection, :action => :howto
  end

  root :to => 'wishes#owner_protection'
end

app/models/wish.rb
class Wish < ActiveRecord::Base
  attr_accessible :notes, :title, :url, :image, :image_cache, :position, :received_on, :public, :price

  validates :secret, :presence => true, :uniqueness => true

  before_validation :create_secret

  mount_uploader :image, ImageUploader

  acts_as_list

  private

  def create_secret
    unique_id = nil
    begin
      unique_id = SecureRandom.uuid # or whatever you chose like UUID tools
    end while unique_id.nil? || self.class.exists?(:secret => unique_id)
    self.secret = unique_id
  end
end

app/controllers/admin/wishes_controller.rb
class Admin::WishesController < ApplicationController
  # taken from railscast 270 :D You obviously want to change it
  http_basic_authenticate_with :name => "frodo", :password => "thering", :realm => I18n.t('admin_wishes_controller.http_basic_auth_realm')

  layout "admin"

  # GET /admin/wishes
  def index
    @wishes = Wish.order('wishes.position ASC')
  end

  # GET /admin/wishes/1
  def show
    @wish = Wish.find(params[:id])
  end

  # GET /admin/wishes/new
  def new
    @wish = Wish.new
  end

  # GET /admin/wishes/1/edit
  def edit
    @wish = Wish.find(params[:id])
  end

  # POST /admin/wishes
  def create
    @wish = Wish.new(params[:wish])

    if @wish.save
      redirect_to admin_wish_url(@wish), notice: I18n.t('admin_wishes_controller.wish_created_notice')
    else
      render action: "new"
    end
  end

  # PUT /admin/wishes/1
  def update
    @wish = Wish.find(params[:id])

    if @wish.update_attributes(params[:wish])
      redirect_to admin_wish_url(@wish), notice: I18n.t('admin_wishes_controller.wish_updated_notice')
    else
      render action: "edit"
    end
  end

  # DELETE /admin/wishes/1
  def destroy
    @wish = Wish.find(params[:id])
    @wish.destroy
    redirect_to admin_wishes_url
  end

  # POST /admin/wishes/sort
  def sort
    @wishes = Wish.all
    @wishes.each do |w|
      w.position = params[:wish].index(w.id.to_s) + 1
      w.save
    end

    render :nothing => true
  end

  def toggle_public
    @wish = Wish.find(params[:id])
    @wish.public = !@wish.public
    @wish.save
    redirect_to admin_wishes_url, :notice => I18n.t('admin_wishes_controller.wish_updated_notice')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController

  def owner_protection
  end

  def owner
    cookies[:visitor] = false
    redirect_to wishes_url
  end

  def visitor
    cookies[:visitor] = true
    redirect_to wishes_url
  end

  def howto
  end

  # GET /wishes
  def index
    order = if cookies[:visitor] && cookies[:visitor] === 'true' # cookies actually are strings.
      "wishes.claimed_by DESC, wishes.position ASC"
    else
      "wishes.position ASC"
    end

    @wishes = Wish.find(:all, :conditions => {:public => true}, :order => order)
  end

  # GET /wishes/1
  def show
    begin
      @wish = Wish.find(params[:id], :conditions => {:public => true})
    rescue ActiveRecord::RecordNotFound => e
      logger.warn e
      redirect_to root_url, :notice => I18n.t('wishes_controller.wish_not_found')
    end
  end

  # POST /wishes/1/prepare_claim
  def prepare_claim
    @wish = Wish.find(params[:id])
    ClaimMailer.claim(@wish, params[:claim][:email]).deliver
    redirect_to @wish, :notice => I18n.t('wishes_controller.prepare_claim_notice')
  end

  # GET /wishes/ae2342ac/claim
  def claim
    @wish = Wish.find_by_secret(params[:id])
    if @wish.claimed_by.nil?
      @wish.claimed_by = params[:email]
      @wish.save
      ClaimMailer.claimed_successfully(@wish, params[:email]).deliver
      notice = I18n.t('wishes_controller.claim_notice', :title => @wish.title)
    else
    notice = I18n.t('wishes_controller.claim_failed_notice', {:title => @wish.title, :email => @wish.claimed_by})
    end
    redirect_to @wish, :notice => notice
  end
end

app/helpers/admin/wishes_helper.rb
module Admin::WishesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/admin/wishes/_form.html.erb
<%= form_for(@wish, :url => (@wish.id ? admin_wish_url(@wish) : admin_wishes_url)) do |f| %>
  <% if @wish.errors.any? %>
    <div id="error_explanation">

      <%
      #TODO should get localized 
      %>
      <h2><%= pluralize(@wish.errors.count, "error") %> prohibited this wish from being saved:</h2>

      <ul>
      <% @wish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :public %><br />
    <%= f.check_box :public %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/wishes/edit.html.erb
<h1><%= t('admin_wishes_views.edit_wish_title') %></h1>

<%= render 'form' %>

<%= link_to 'Show', @wish %> |
<%= link_to 'Back', admin_wishes_path %>

app/views/admin/wishes/index.html.erb
<h1><%= t('admin_wishes_views.index_title') %></h1>

<table id="admin-wishlist">
<% @wishes.each do |wish| %>
  <tr id="wish_<%= wish.id %>">
    <td><%= image_tag wish.image.thumb.url.to_s %></td>
    <td>
      <%= raw wish.public ? '' : "<span class='secret'>#{t('labels.secret')}</span>" %>
      <span class="price"><%= wish.price %></span>
      <strong><%= wish.title %></strong><br>
      <%= wish.notes %>
    </td>
    <td>
      <%= link_to t('actions.show'), admin_wish_path(wish) %><br>
      <%= link_to t('actions.edit'), edit_admin_wish_path(wish) %><br>
      <%= link_to t('actions.toggle_public'), toggle_public_admin_wish_path(wish), method: :post %>
      <%= link_to t('actions.destroy'), admin_wish_path(wish), method: :delete, data: { confirm: t('actions.confirm_delete_wish', :title => wish.title) } %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('actions.new'), new_admin_wish_path %>

<% content_for :javascript do %>
  <%= javascript_tag do %>
  // Sorting
  $(document).ready(function(){
    $('#admin-wishlist').sortable({
      axis: 'y',
      dropOnEmpty: false,
      cursor: 'crosshair',
      items: 'tr',
      opacity: 0.4,
      scroll: true,
      placeholder: 'sortable-placeholder',
      update: function(){
        $.ajax({
          type: 'post',
          data: $(this).sortable('serialize'),
          dataType: 'script',
          complete: function(request){
            $('#admin-wishlist').effect('highlight');
          },
          url: '/admin/wishes/sort'
        })
      }
    });
  });
  <% end %>
<% end %>

app/views/admin/wishes/new.html.erb
<h1><%= t('admin_wishes_views.new_wish_title') %></h1>

<%= render 'form' %>

<%= link_to t('actions.back'), admin_wishes_path %>

app/views/admin/wishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= t('active_record.attributes.wish.title') %></b>
  <%= @wish.title %>
</p>

<p>
  <b><%= t('active_record.attributes.wish.notes') %></b>
  <%= @wish.notes %>
</p>

<p>
  <b><%= t('active_record.attributes.wish.url') %></b>
  <%= @wish.url %>
</p>

<%= link_to t('actions.edit'), edit_admin_wish_path(@wish) %> |
<%= link_to t('actions.back'), admin_wishes_path %> |
<%= link_to t('actions.wish_in_frontend'), wish_path(@wish) %> |
<%= link_to t('actions.all_wishes_in_frontend'), wishes_path %>

app/views/layouts/_header.html.erb
<header>
  <img src="/assets/header.png" alt="Wishlist">
</header>

<% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
<% end %>
<% if flash[:error] %>
    <p class="error"><%= flash[:error] %></p>
<% end %>

<nav>
  <ul>
    <li><a href="/">Start</a></li>
  </ul>
</nav>

app/views/layouts/_wishlist.html.erb
<section id="wishlist">
  <%= yield %>
</section>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wishlist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery-ui-1.10.3" %>
  <%= yield :javascript %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="page">

    <%= render 'layouts/header' %>

    <div id="content">
      <%= yield %>
    </div>

  </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wishlist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="canvasContainer">
    <canvas id="canvas"></canvas>
  </div>

  <div id="page">

    <%= render 'layouts/header' %>

    <div id="content">

      <%= render 'layouts/wishlist' %>

    </div>

  </div>

</body>
</html>

app/views/wishes/_claim.html.erb
<%= form_tag(prepare_claim_wish_url(:id => wish), :method => 'post') do %>
  <fieldset>
    <%= label_tag :claim_email, t('wishes_views.claim_label') %>
    <%= email_field(:claim, :email) %>
    <%= submit_tag(t('actions.claim'), class: 'button') %>
  </fieldset>
<% end %>

app/views/wishes/_header.html.erb
<%
 # it's recommended that you add your own header in here.
 # this will be included right below the headline and before your
 # actual wishes.
 #
 # it's common practise to make a personal statement or include an
 # image of yourself, here. Just go nuts.
%>
<!-- personal statement is a go! -->
<p>insert a personal statement here</p>

app/views/wishes/howto.de.html.erb
<h1>Wissenswertes</h1>
<h2>Wozu ist der Wunschzettel gut?</h2>
<p>Der Wunschzettel listet mögliche Geschenke auf. Jeder Besucher kann Geschenke von der Liste nehmen, so werden sie nicht doppelt geschenkt.</p>
<h2>Verdirbt das nicht die Überraschung?</h2>
<p>Nein, die Liste funktioniert ähnlich wie zum Beispiel die Amazon-Wunschliste: Der Inhaber sieht im Normalfall nicht, was von der Liste "verschwindet".</p>
<h2>Woher bekomme ich die Geschenke?</h2>
<p>Der Wunschzettel gehört zu keinem Shop, du musst also selbst herausfinden, woher du die Geschenke tatsächlich bekommst. Oft ist in der Beschreibung ein Hinweis. In vielen Fällen stellst du besser einen Gutschein aus.</p>
<h2>Wie ist der Ablauf?</h2>
<ul>
<li>Suche dir etwas auf der Liste aus.</li>
<li>Klicke auf "<%=t "actions.give_this_item" %>"</li>
<li>Trage deine E-Mailadresse ein und clicke auf "<%=t "actions.claim" %>".</li>
<li>Du erhälst nun eine E-Mail auf die zuvor eingegebene Adresse.</li>
<li>Bitte öffne die E-Mail und klicke den darin enthaltenen Link an. Damit wird der Wunsch vom öffentlichen Wunschzettel entfernt.</li>
<li>Du erhälst eine zweite E-Mail als Bestätigung, dass alles geklappt hat.</li>
</ul>
<p>Bitte beachte, dass es sich hier nicht um einen Shop handelt. Du musst dich also selbst noch darum kümmern, wo du das Geschenk (oder einen Gutschein dafür) her bekommst.
<h2>Ich möchte auch so einen Wunschzettel</h2>
<p>Der Wunschzettel ist ein Open Source Projekt, und den Quellcode dazu gibt es auf <a href="https://github.com/ccoenen/wishlist">Github</a>! Momantan sind dafür aber leider noch Programmierkenntnisse nötig.</p>

app/views/wishes/howto.en.html.erb
<h1>How does the wishlist work?</h1>
<%
 # fixme: write this howto / translate it to english
%>

app/views/wishes/index.html.erb
<h1><%= t('wishes_views.index_title') %></h1>
<%= render :partial => 'header' %>
<% if @wishes.empty? %>
  <p><%=t 'wishes_views.empty_list' %></p>
<% end %>
<ul class='records'>
<% @wishes.each do |wish| %>
   <%
  if cookies[:visitor] && cookies[:visitor] != 'true'
    wish.claimed_by = nil
    wish.readonly!
  end
  %>
  <li class='record <%= 'claimed' if wish.claimed_by %>'>
    <%= image_tag wish.image.thumb.url.to_s, class: 'thumb' %>
    <div class='info'>
      <h4><%= wish.title %></h4>
      <span class='notes'><%= wish.notes %></span>
      <span class='url'><%= link_to wish.url, wish.url %></span>
	  <span class='price'><%= wish.price %></span>
      <% if !wish.claimed_by %>
        <%= link_to t('actions.give_this_item'), wish, class: 'button' %>
      <% else %>
        <span class="claimed" title="<%= t('labels.claimed_title') %>"><%= t('labels.claimed') %></span>
      <% end %>
    <div>
  </li>
<% end %>
</ul>

app/views/wishes/owner_protection.html.erb
<h1><%= t('wishes_views.owner_protection_title') %></h1>
<p><%= t('wishes_views.owner_protection_explanation') %></p>
<%= link_to t('wishes_views.owner_show_all'), {:controller => :wishes, :action => :owner}, :class => "button" %><br>
<%= link_to t('wishes_views.visitor_show_unclaimed'), {:controller => :wishes, :action => :visitor}, :class => "button" %><br>
<%= link_to t('wishes_views.howto'), {:controller => :wishes, :action => :howto}, :class => "button howto" %>

app/views/wishes/show.html.erb
<h2><%= @wish.title %></h2>
<span class="pricetag"><%= @wish.price %></span>
<%= image_tag @wish.image.thumb.url.to_s, class: 'thumb' %>

<p>
  <%= @wish.notes %>
</p>

<p>
  <%= link_to @wish.url, @wish.url %>
</p>

<%= render :partial => 'claim', :locals => {:wish => @wish} %>

<%= link_to t('actions.back'), wishes_path, class: 'button' %>